# Generated by Django 5.2.7 on 2025-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_codigoverificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresausuario',
            name='es_admin_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
