# Generated by Django 5.2.7 on 2025-11-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('linea', models.CharField(blank=True, max_length=50)),
                ('modelo', models.PositiveIntegerField()),
                ('capacidad_pasajeros', models.PositiveIntegerField(default=0)),
                ('soat_vencimiento', models.DateField(blank=True, null=True)),
                ('tecnomecanica_vencimiento', models.DateField(blank=True, null=True)),
                ('poliza_contractual_vencimiento', models.DateField(blank=True, null=True)),
                ('poliza_extracontractual_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='inicio.empresa')),
            ],
        ),
    ]
