# Generated by Django 5.2.7 on 2025-11-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='licencia_categoria',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='tipo_documento',
            field=models.CharField(help_text='Ej: CC, CE, TI', max_length=5),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='es_admin_empresa',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('tipo_servicio', models.CharField(blank=True, help_text='Ej: escolar, empresarial, turismo…', max_length=50)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_contacto', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='inicio.conductor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='inicio.empresa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='inicio.vehiculo')),
            ],
        ),
    ]
